### ISSUE TITLE
GPS doesn't seem to work

### ISSUE THREAD

**Issue by paxtontech** [CyanogenMod/android_device_motorola_victara#3]
Good afternoon! I'm using 12.1 from 5-10 and am unable to get the device GPS to function. It "turns on" but when using an application that utilizes the GPS, no information is received. I didn't see anything in the change logs recently that looked like it might have affected it.

**Comment by raymon-pdx** [comment]
Hi Travis,

Please refer to a closed issue here: https://github.com/CyanogenMod/android_device_motorola_victara/issues/1

let me know if that solves the problem.
