### ISSUE TITLE
plz make some changes for the devices for china (xt1085) 

### ISSUE THREAD

**Issue by leehz** [CyanogenMod/android_device_motorola_victara#4]
it was almost the same with the global version like xt 1092 xt1095 xt1096 xt1097 ...

**Comment by leehz** [comment]
if anything i can do, plz let me know .... happy for your good news ..

**Comment by PeterCxy** [comment]
@leehz You just flash the gpt.bin of XT1095/1092 in fastboot (fastboot flash partition gpt.bin) and then XT1085 can just be treated like XT1095.
