### ISSUE TITLE
cm cannot be flashed in xt1085(china version)

### ISSUE THREAD

**Issue by leehz** [CyanogenMod/android_device_motorola_victara#5]
BoardConfig.mk

BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00A00000 (cm version)
BOARD_BOOTIMAGE_PARTITION_SIZE := 10444800 (can be used for china)

as far as i know. hope it will help

**Comment by PeterCxy** [comment]
I believe flashing gpt.bin of XT1095 into XT1085 is a better choice as this CM ROM is built for global version. See my comment on your another issue for details.

**Comment by leehz** [comment]
@PeterCxy  tks, bro.
